### ISSUE TITLE
Review - Quest 1/4

### ISSUE THREAD

**Issue by eric-anderton-at-rearc** [michael-ell-rearc/data-quest#2]
Comments for review.

**Comment by eric-anderton-at-rearc** [comment]
https://github.com/michael-ell-rearc/data-quest/blob/aeb238b5f55276c3d93fb1e220899d2baeb81019/scripts/task_one.py#L25

```
  search = findall('(\d{1,2}\/\d{1,2}\/\d{2,4}\s\s\d{1,2}:\d{2}\s[P|A]M)[\s,\d]*\<A HREF\=\"[\w,\d,\.,\/]*\"\>(pr\.[\w,\d,\.]*)',response.data.decode('UTF-8'),IGNORECASE)
```

A few things stand out here.

* Forward slash doesn't need to be escaped - this isn't a `sed` expression. ;)
* No need for `,` inside the `[...]` expressions; they don't actually separate anything.  As written these will just match the commas themselves, along with the other characters and character classes.
* I get the kludge here to extract tag content.  It may make more sense to use BeautifulSoup (or some other HTML parser) instead, as its more robust for this job.
* Use a negative character match to make attribute parsing more reliable.  Change `"[\w,\d,\.,\/]*\"\` to `"[^"]*"`
* Expression assumes no characters between href attribute value and the end of the tag.  Probably should put `[^>]*` in there to be safe.
* Expression assumes single space between `<A` and href attribute.

**Comment by eric-anderton-at-rearc** [comment]
https://github.com/michael-ell-rearc/data-quest/blob/1cb6e9625d8ef2bf1cbaed24e277021fcf830420/scripts/task_one.py#L74

Move the S3 bucket name to a var at the top of the script to improve re-usability.  Just like you did with `SOURCE_URL`.

**Comment by eric-anderton-at-rearc** [comment]
https://github.com/michael-ell-rearc/data-quest/blob/1cb6e9625d8ef2bf1cbaed24e277021fcf830420/scripts/task_one.py#L93

I think this can be shortened to:

```
Body=json.dumps(manifest)
```

That said, I'm not sure if the round-trip from bytes->utf-8->bytes is side-effect free.  I assume the JSON marshalling process would change wide characters to escape sequences in strings, leaving the output completely 7-bit clean (no BOM, no UTF-16, etc).

Alternately, the docs say there's a `bytes()` variant that takes an encoding:  `bytes(string, encoding[, errors]) -> bytes`.

**Comment by michael-ell-rearc** [comment]
Thanks. I pulled some of the regex advice in and just made a quick adjustment :) (the pre-review code is still under the old step-one branch)
